<?php

namespace Database\Seeders;

use App\Models\Division;
use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $data = [
            ['nama' => 'Mulyono', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Ahmad Fatoni', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Dwi Santosa', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Ahmad Saiful Huda', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Edi Suwanto', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Aseptian Ridho Ardiansyah', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Ismail Hidayatullah', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Moch Andrean', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Tomi Yulianto', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Artha Rohman Syaid', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Achmad Mulyadi', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'M Nur Kholis', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Muhammad Iksan Arif', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Eko Agus Prasetyo', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Sasputro', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Slamet Prayugo', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Umri Udin', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Muhammad Toyib', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Chafid Zulkifli', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Achmad Syafian', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Akhmad Afif Fauqi', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Slamet Supriono', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'MKH Riyanto', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Edi Sutikno', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Yudi Bagus Nurokhim', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Dwi Jatmiko', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Adib Zainul Mustafit', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Mahardika Angga Pratama', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'M. Yahya', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Achmad Busiri', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Mochammad Syaiful Arifin', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Ario Susilo', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Moh. Nasrullah', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Muhammad Fais Alqurni', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Rizky Riswanto', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Ahmad Muamal Fajri', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Mochamad Cholilullah', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Aries Hadi Wijaya', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Anang Kosim', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Siswo Ariyanto', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => "Imam Syafi'i", 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Dodi Zakaria', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Dede Faisal Ramadan', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Agung Sutrisno', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Muhammad Irhamni', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Wahyu Firmansyah', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Deni Iswanto', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Supriyanto', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Agus Setiawan', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Muhammad Didik Mustakim', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Muchammad Chakiki', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Mochamad Bisri Mustofa', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Rosidin', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Arif Wicaksono', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'M. Bima Fani Anggara', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Hendryk Rahmawan', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'M. Amin Mada Arie Baya', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Ahmat Samsul Arifin', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Ahmad Sairozi', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Zainul Arifin', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Achmad Zakariyah', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Ali Hidayat', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Apriyanto', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Muhammad Aminudin', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Rizal Ardiansyah', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Chandra Surya Lesmana', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Elda Sasmita', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Roni Puji Purwanto', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Irham Rahmadhani', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'M Khisom', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => "Mukhammad Mas'udi", 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Muchamad Yanto', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Imam Hanafi', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Mohammad Cholid', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Agung Santoso', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Albertus Ifan Setiawan', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Irwansyah Aprilliyanto', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Iip Dwi Prasetyan Umiatun', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Wildan Egga Pratama', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Yulio Angga Andika Putra', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Feri Fajar Ferdiansyah', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Mokhamad Sakroni', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Khoirul Ikbal', 'status' => 'Permanent', 'division' => 'Painting'],
            ['nama' => 'Achmad Nur Cahyo', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Hendro Prasetyo', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Mochammad Syaifudin', 'status' => 'Permanent', 'division' => 'Assembling'],
            ['nama' => 'Nur Cholis', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'M. Taufiq Hidayat', 'status' => 'Permanent', 'division' => 'DST'],
            ['nama' => 'Akhmad Liqul Ansori', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Mokhamad Dwi Mustofa', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Mochammad Ulil Abshor', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Mokhammad Andi Khoirudin', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Ahmad Habib As Sahab', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Yoga Puja Nirwana', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Delvi Hafiludin', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Mukhammad Roudon', 'status' => null, 'division' => 'DST'],
            ['nama' => 'Krisna Adi Purnama', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Nasoikhul Firdaus', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Dedy Haryanto', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Fiqri', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Moch. Novan Dwi Yudianto', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Anfa Dhio Frihandipa', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Muhammad Yusril', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'M. Syahrul Syaifani', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Bahroni Syafrizal', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Bayu Adi Saputra', 'status' => null, 'division' => null],
            ['nama' => 'Mochammad Zainur Roziqin', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Muhammad Fatkhul Jinan', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Chalvin Yudha Ayiyin', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Mukhammad Arif Pratama', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Jumiati', 'status' => null, 'division' => 'DST'],
            ['nama' => 'Ainun Qolby Sulistiyo Putri', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Eka Nadya Fatmawati', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Mohammad Riszki Alan Pratama', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Muhammad Nasihudin', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Achmad Riadin', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Mukhammad Priyanto', 'status' => null, 'division' => 'DST'],
            ['nama' => 'Wahyu Setio Budi Hutomo', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Angga Bagus Maulana', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Tamhid Masaji', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Kris Liswantari', 'status' => null, 'division' => 'DST'],
            ['nama' => 'Hari Setiawan', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'M. Nadif', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Nur Amin', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Alfin Mahendra', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Wisnu Adi Rinenggo', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Moh Sulkhan Ashari', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Nurhasan', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Yusuf Pratama', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Mochammad Djati Kemal', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Moch. Haikal Lutfi', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Laksana Syair Achmadi', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Abdul Rohim', 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Susilowati', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Indah Afiati', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Fatimatuz Zahro', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Mukhamad Junaedi', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Dinda Lukita Sari', 'status' => null, 'division' => 'Assembling'],
            ['nama' => 'Muhammad Hasbi', 'status' => null, 'division' => 'DST'],
            ['nama' => 'A. Taufiqurrohman', 'status' => null, 'division' => 'Assembling'],
            ['nama' => "Mohammad Mi'raj Akbar", 'status' => null, 'division' => 'Painting'],
            ['nama' => 'Achmad Nur Huda', 'status' => null, 'division' => 'DST'],
            ['nama' => 'M. Pandu Gautama Wiranagara', 'status' => null, 'division' => 'DST'],
            ['nama' => 'Nisa Aulia', 'status' => null, 'division' => 'DST'],

        ];

        foreach ($data as $employee) {
            $divisionId = DB::table('divisions')->where('nama', $employee['division'])->value('id');

            DB::table('employees')->insert([
                'nama' => $employee['nama'],
                'division_id' => $divisionId,
                'status' => $employee['status'],
            ]);
        }
    }
}
